// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMWUpytaEHpykTDDXsCNYTIjTD5-4h0AA',
    appId: '1:1043234910102:web:8bce53cba2080fe048f7b7',
    messagingSenderId: '1043234910102',
    projectId: 'myfristproject-dd7da',
    authDomain: 'myfristproject-dd7da.firebaseapp.com',
    storageBucket: 'myfristproject-dd7da.firebasestorage.app',
    measurementId: 'G-2Y1JNER5TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmsZFAuEUr8Olj9bYpVIvgiyVhC5rZkR0',
    appId: '1:1043234910102:android:9b3b6e97f36b8d8f48f7b7',
    messagingSenderId: '1043234910102',
    projectId: 'myfristproject-dd7da',
    storageBucket: 'myfristproject-dd7da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL8G6WH6PcIGgSmlYdRG6qo1x6noNUrCY',
    appId: '1:1043234910102:ios:a7138dbb8fe2590a48f7b7',
    messagingSenderId: '1043234910102',
    projectId: 'myfristproject-dd7da',
    storageBucket: 'myfristproject-dd7da.firebasestorage.app',
    iosClientId: '1043234910102-oo0grnac19f2k77nitc0cc6uj7549fkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.notifLearn',
  );
}
